version: "3"
services:

  green:
    container_name: green
    build:
      context: .
      dockerfile: Dockerfile
      # reference docker target
      target: release
    restart: unless-stopped
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT} || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      SRT_URL: ${SRT_URL}
      RTMP_URL: ${RTMP_URL}
      PORT: ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}